import os
import json
import urllib.request

# ================= Configuration =================
REPO = "Arlia-Etoile/Diversion-Rule-List"
BASE_URL = "https://r.arlia.cn.mt"
BRANCHES = ["mrs", "lsr", "yaml"] 
# 目标改为独立的文件
OUTPUT_FILE = "LINKS.md"
# =================================================

def get_files_in_branch(branch):
    """Fetch file paths via GitHub API"""
    url = f"https://api.github.com/repos/{REPO}/git/trees/{branch}?recursive=1"
    req = urllib.request.Request(url)
    token = os.getenv("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    
    try:
        with urllib.request.urlopen(req) as response:
            data = json.loads(response.read().decode())
            valid_exts = ('.yaml', '.mrs', '.lsr')
            return sorted([
                item['path'] for item in data.get('tree', []) 
                if item['type'] == 'blob' and item['path'].lower().endswith(valid_exts)
            ])
    except Exception as e:
        print(f"⚠️ Skip branch {branch}: {e}")
        return []

def main():
    # 构建新文件的完整内容
    content = "# 🔗 Subscription Links\n\n"
    content += "> This file is automatically generated by GitHub Actions. Copy these links to your proxy clients.\n\n"
    content += "---\n\n"

    for branch in BRANCHES:
        files = get_files_in_branch(branch)
        if not files:
            continue
        
        content += f"## 📁 {branch.upper()} Rules\n\n"
        content += "| Rule Set | Type | Subscription Link |\n"
        content += "| :--- | :---: | :--- |\n"
        
        for file_path in files:
            file_name = file_path.split('/')[-1]
            rule_set = os.path.splitext(file_name)[0]
            ext = os.path.splitext(file_name)[1][1:].upper()
            link = f"{BASE_URL}/{branch}/{file_path}"
            content += f"| `{rule_set}` | `{ext}` | {link} |\n"
        
        content += "\n"

    # 直接全量写入（不再需要寻找标记，直接覆盖生成最新的）
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    
    print(f"🚀 {OUTPUT_FILE} has been fully regenerated.")

if __name__ == "__main__":
    main()
